---

base_archiving_tools:
  - mpack
  - p7zip-full
  - p7zip-rar
  - rar
  - sharutils
  - unace
  - unrar
  - unzip
  - uudeview
  - zip

base_productivity_tools:
  - libreoffice

base_system_tools:
  - progress
  - pwgen
  - pavucontrol
  - rename
  - pass
  - gpgv2
  - pinentry-tty
  - pinentry-gq
  - direnv
  # - syncthing

base_system_tools_laptop:
  # - cpufrequtils
  # - powertop
#  - tp-smapi-dkms  # for older ThinkPads

base_download_tools:
  - speedtest-cli
  - wget

base_developer_tools:
  - ansible
  - ansible-lint
  - awscli
  - bat
  - bpython
  - black
  - cloc
  - clusterssh
  - colordiff
  - curl
  - default-jre-headless
  - dos2unix
  - entr
  - expect
  - filezilla
  - fonts-powerline
  - g++
  - gedit-plugins
  - geoip-bin
  - ghostwriter
  - git
  - git-extras
  - gitg
  - golang-go
  - htop
  - httpie
  - inotify-tools
  - ipython3
  - jq
  - kwalify
  - makeself
  - meld
  - miller
  - most
  - ncat
  - netcat
  - nmap
  - nodejs
  - pandoc
  - parallel
  - pep8
  - pipenv
  - powerline
  - pry
  - pssh
  # - puppet
  # - puppet-lint
  - pv
  - pylint
  - python3-demjson  # provides jsonlint-py3 for json lint
  - python3-jmespath
  - python3-pep8
  - python3-pip
  - ranger
  - recode
  - remmina
  - rename
  - ruby
  - ruby-dev
  - shellcheck
  - siege
  - socat
  - sshfs
  - sshpass
  - tilix
  - tldr
  - tmux
  - tmuxp
  - tree
  - uget
  - yamllint
  - google-chrome-stable
  - chromium-browser
  - awesome
  - awesome-extra
  - fonts-font-awesome
  - keychain

base_virtualization_tools:
  # - virtualbox
  # - virtualbox-ext-pack
  # - docker.io
  #  - docker-ce
  #  - docker-compose

base_media_tools:
  - ffmpeg
  - gimp
  - imagemagick
  - libimage-exiftool-perl
  - mediainfo
  - soundconverter
  # - ubuntu-restricted-extras
  - vlc

base_git_bash_prompt_url: "https://github.com/magicmonty/bash-git-prompt.git"

base_openssh_server:
  apt_package: openssh-server
  service: ssh
...
